{% set version = '2.0.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-biclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/biclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/biclust/biclust_{{ version }}.tar.gz
  sha256: 6b20f258b581af3229fb94bb1eda001d8b1498c8dc70621961139247f9ae67de

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-additivitytests
    - r-colorspace
    - r-flexclust
    - r-ggplot2
    - r-lattice
    - r-tidyr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-additivitytests
    - r-colorspace
    - r-flexclust
    - r-ggplot2
    - r-lattice
    - r-tidyr

test:
  commands:
    - $R -e "library('biclust')"           # [not win]
    - "\"%R%\" -e \"library('biclust')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=biclust
  license: GPL-3
  summary: 'The main function biclust() provides several algorithms to find biclusters in two-dimensional
    data: Cheng and Church (2000, ISBN:1-57735-115-0), spectral (2003) <doi:10.1101/gr.648603>,
    plaid model (2005) <doi:10.1016/j.csda.2004.02.003>, xmotifs (2003) <doi:10.1142/9789812776303_0008>
    and bimax (2006) <doi:10.1093/bioinformatics/btl060>. In addition, the package provides
    methods for data preprocessing (normalization and discretisation), visualisation,
    and validation of bicluster solutions.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: biclust
# Version: 2.0.2
# Date: 2020-02-03
# Author: Sebastian Kaiser, Rodrigo Santamaria, Tatsiana Khamiakova, Martin Sill, Roberto Theron, Luis Quintales, Friedrich Leisch and Ewoud De Troyer.
# Maintainer: Sebastian Kaiser <dr.sebastian.kaiser@gmail.com>
# Title: BiCluster Algorithms
# Depends: R (>= 2.10), MASS, grid, colorspace, lattice
# Imports: methods, flexclust, additivityTests, tidyr, ggplot2
# Suggests: isa2
# Description: The main function biclust() provides several algorithms to find biclusters in two-dimensional data: Cheng and Church (2000, ISBN:1-57735-115-0), spectral (2003) <doi:10.1101/gr.648603>, plaid model (2005) <doi:10.1016/j.csda.2004.02.003>, xmotifs (2003) <doi:10.1142/9789812776303_0008> and bimax (2006) <doi:10.1093/bioinformatics/btl060>. In addition, the package provides methods for data preprocessing (normalization and discretisation), visualisation, and validation of bicluster solutions.
# License: GPL-3
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2020-02-03 14:44:44 UTC; n349570
# Repository: CRAN
# Date/Publication: 2020-02-04 17:30:02 UTC
