appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: SvGTBGsHiQY22Cf2fcy32BoICBQRR04SiaQSPffFTCmjs0ibfjJP+UsvaND2QuVGMOsOfWalHsQFLCHmDZuO/+ME83/Lown8VH4+9q1XpPT76C2wqY0k/zZ03WQH8CkBnC/2UgWSyJWAUFwngp9VSah8TRR9FcRqqJ2utQhbI+MsZPtDMNuW7CWZMRzzxXvHND6X7+1B5zGkLgOZUgVoLt+nAji6NF014k4rqUC6AKnajIMx0SGE6b9Njla0mErQPR7Nzk73nBoJWaMayVdFD+g7vMs5P979npduiqim5+TteZDodNea/uv1rLp9I/3U3YHl1gusWHfbtC+0YPxSop9iGv7q/dD5w5RmhX3o5Eu51HO5ya5JtfxlWl35fCz4bX7jOSxDPSyHEhMlFO6PtAZDlrIQZkP+1LYx3zShPAIEzIwJVRre8EKCpoXwhNovRxdQ91q6f2E/SQJrJLDd8HVHUHwwXGoI8deU/P+smbeqTR2gxTqc6ZNPZBv3i0QSZFee7NY9ogdb/hbVAcT5MtzvDBY3qQkItQ1EeXtowFhRmWOqGrn0WITRqwRPRS6cUAddJsGIdMq9hGNTaurN1GMp2jaBhuFsZrZgGTw8GNUY5eqK2Vs/dfzc3T/ujdMJsrCDcZJ0HtO4SR+CPLr/JZWa3YxGi8tvLKNal2m6xSo=
conda_forge_output_validation: true
